language: node_js
node_js: stable

install: npm install

script:
  - cat .travis.yml
  - ls
  - npm run build
  - cp CNAME ./build
  - cd ./build
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Build"
  - git push --force https://${token}@github.com/twesix-website/www.twesix.cn master